import { View } from "react-native";
import { Stack } from "expo-router";
import { StackScreen } from "@/components/layout/screen";
import { SectionTitle } from "@/components/ui";
import { AqiHelpChat } from "@/features/aqi-help/AqiHelpChat";

export default function AqiHelpScreen() {
  return (
    <StackScreen scroll={false}>
      <Stack.Screen options={{ title: "aqiHelp", headerBackTitle: "Back" }} />
      <SectionTitle
        eyebrow="Guidance from published resources"
        title="aqiHelp"
        lede="Ask a plain-language question about air, heat, rain, alerts, or Climate Compass. Answers are generated by AI from published guides — not a live operator — and are not medical or official advice."
      />
      <View className="min-h-0 flex-1">
        <AqiHelpChat />
      </View>
    </StackScreen>
  );
}
